{% set version = "0.52" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-l1pack
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/L1pack_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/L1pack/L1pack_{{ version }}.tar.gz
  sha256: 039ebd57500c9d75c2914090b87059110c72c131b465381ffa99b4999c406256

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fastmatrix
  run:
    - r-base
    - r-fastmatrix

test:
  commands:
    - $R -e "library('L1pack')"           # [not win]
    - "\"%R%\" -e \"library('L1pack')\""  # [win]

about:
  home: http://l1pack.mat.utfsm.cl/
  license: GPL-3.0-only
  summary: L1 estimation for linear regression, density, distribution function, quantile function and random number generation for univariate and multivariate Laplace distribution.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - PelzKo
